name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
body:
  - type: markdown
    attributes:
      value: "Thank you for suggesting a new feature!"

  - type: textarea
    id: problem
    attributes:
      label: Is your request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired Solution
      description: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've thought about.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, mockups, or any other context.
